[build]
  command = "npm run build"
  publish = "dist/public"

# DESACTIVAR empaquetado de dependencias
[functions]
  directory = "server"
  node_bundler = "none"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200
