[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "server"
  node_bundler = "esbuild"

# Habilitar ESM
[functions.*]
  format = "esm"

# MÃ³dulos que Netlify no puede resolver
[functions.nodejs_compat]
  external_node_modules = ["@neondatabase/serverless", "ws"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
