[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "server"
  node_bundler = "esbuild"

# Permitir ESM en funciones
[functions."*"]
  format = "esm"

# Compatibilidad para m√≥dulos externos
[functions.nodejs_compat]
  external_node_modules = ["@babel/preset-typescript"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
